/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebarBoltPy: [
    {
      type: 'html',
      value: '<h3>Bolt for Python</h3>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    'getting_started',
    {type: 'html', value: '<hr>'},
    {
      type: 'category',
      label: 'Basic concepts',
      items: [
        'basic/listening_messages',
        'basic/sending_messages',
        'basic/listening_events',
        'basic/web_api',
        'basic/listening_actions',
        'basic/responding_actions',
        'basic/acknowledging_requests',
        'basic/listening_responding_shortcuts',
        'basic/listening_responding_commands',
        'basic/opening_modals',
        'basic/updating_pushing_modals',
        'basic/listening_modals',
        'basic/publishing_views',
        'basic/listening_responding_options',
        'basic/authenticating_oauth',
        'basic/socket_mode'
      ],
    },
    {
      type: 'category',
      label: 'Advanced concepts',
      items: [
        'advanced/adapters',
        'advanced/custom_adapters',
        'advanced/async',
        'advanced/errors',
        'advanced/logging',
        'advanced/authorization',
        'advanced/token_rotation',
        'advanced/listener_middleware',
        'advanced/global_middleware',
        'advanced/context',
        'advanced/lazy_listener',
        ],
    },
    {
      type: 'category',
      label: 'Workflow steps (Deprecated)',
      items: [
        'steps/workflow_steps_overview',
        'steps/executing_workflow_steps',
        'steps/creating_workflow_step',
        'steps/adding_editing_workflow_step',
        'steps/saving_workflow_step',
      ],
    },
    {type: 'html', value: '<hr>'},
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/getting_started_http'
      ],
    },
    {type: 'html', value: '<hr>'},
    {
      type: 'link',
      label: 'Reference',
      href: '/api-docs/slack_bolt/',
    },
    {type: 'html', value: '<hr>'},
    'Changelog',
    {
      type: 'link',
      label: 'Code on GitHub',
      href: 'https://github.com/SlackAPI/bolt-python',
    },
    {
      type: 'link',
      label: 'Contributors Guide',
      href: 'https://github.com/SlackAPI/bolt-python/blob/main/.github/contributing.md',
    },
  ],
};

export default sidebars;
