#!/usr/bin/env python
"""Generate the Markdown API reference for slack_bolt using griffe + griffe2md.

Invoked by scripts/generate_api_docs.sh. griffe loads the package, resolves
re-export aliases to their concrete definition, and parses Google-style
docstrings into structured data; griffe2md renders that data to Markdown. This
module is the thin Docusaurus adapter around griffe2md: it walks the package,
writes one Markdown page per module under ``reference/`` (packages become
``index.md``), and post-processes griffe2md's output so the docs site can
compile it as MDX.

The output layout (flattened under ``reference/``, package overviews as
``index.md``) is produced directly. The reference nav is contributed by a
single ``autogenerated`` entry in ``docs/english/_sidebar.json``; this script
writes only Markdown.
"""

import os
import re
import shutil

import griffe
from griffe2md import default_config, render_object_docs

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The API reference lives under the English docs tree. DOCS_BASE_PATH is the
# directory Docusaurus doc IDs are relative to; the reference is written to
# DOCS_BASE_PATH/REFERENCE_SUBDIR.
DOCS_BASE_PATH = os.path.join(REPO_ROOT, "docs", "english")
REFERENCE_SUBDIR = "reference"

# Submodule-overview pages link to their children with absolute Docusaurus
# routes. Those doc IDs resolve relative to the docs root on docs.slack.dev,
# hence the prefix.
SIDEBAR_DOC_ID_PREFIX = "tools/bolt-python/"

PACKAGE = "slack_bolt"


# --------------------------------------------------------------------------- #
# griffe2md rendering
# --------------------------------------------------------------------------- #

# griffe2md renders a griffe object to Markdown. We accept its default output
# style (``## `Name```, ``**Parameters:**``, ``- **app** (App) - ...``) and only
# adjust structural knobs so each module renders as a flat, root-less section
# that slots beneath our own front-matter and submodule links.
CONFIG = dict(default_config)
CONFIG.update(
    docstring_style="google",
    summary=False,
    show_if_no_docstring=False,
    show_submodules=False,
    show_root_heading=False,
    show_root_full_path=False,
    show_root_members_full_path=False,
    show_object_full_path=False,
    heading_level=2,
)


def _render_module(module):
    """Render a module to MDX-safe Markdown via griffe2md + post-processing."""
    return _post_process(render_object_docs(module, CONFIG))


# --------------------------------------------------------------------------- #
# MDX-safety post-processing
# --------------------------------------------------------------------------- #

# Docusaurus v3 parses every .md file as MDX: a bare ``<`` reads as JSX and a
# bare ``{`` as a JS expression, either of which aborts the docs build. Escape
# those two characters in prose while leaving fenced blocks and inline code
# spans untouched.
_CODE_SPLIT_RE = re.compile(r"(```[\s\S]*?```|`[^`]*`)")

# griffe2md wraps type annotations and base classes in ``<code>`` and links
# symbols to intra-page anchors (``#slack_bolt.App``). We render one page per
# module and emit no cross-references, so those anchors don't resolve -- strip
# the wrapper and the anchor links back to plain text
# (``<code>[App](#slack_bolt.App)</code>`` -> ``App``). Links to real URLs
# (``(https://...)``) are left intact.
_CODE_TAG_RE = re.compile(r"</?code>")
_ANCHOR_LINK_RE = re.compile(r"\[([^\]]+)\]\(#[^)]*\)")


def _reflow_indented_code(text):
    """Convert 4-space indented docstring code blocks into fenced python blocks.

    A bare indented block renders without syntax highlighting and, worse, its
    ``<``/``{`` characters would be escaped as prose by _escape_prose. Re-emitting
    the block fenced fixes highlighting and lets the code survive verbatim. Only
    blocks preceded by a blank line are treated as code, matching CommonMark (an
    indented run cannot interrupt a paragraph).
    """
    lines = text.split("\n")
    out = []
    i = 0
    prev_blank = True  # start of a section counts as a preceding blank line
    fence_open = False
    while i < len(lines):
        line = lines[i]
        # Never touch content inside an existing fenced block; just mirror it.
        if line.strip().startswith("```"):
            fence_open = not fence_open
            out.append(line)
            prev_blank = False
            i += 1
            continue
        if fence_open:
            out.append(line)
            prev_blank = False
            i += 1
            continue
        if prev_blank and line.startswith("    ") and line.strip():
            block = []
            while i < len(lines) and (lines[i].startswith("    ") or not lines[i].strip()):
                if lines[i].strip().startswith("```"):
                    break
                block.append(lines[i])
                i += 1
            while block and not block[-1].strip():
                block.pop()
            out.append("```python")
            out.extend(bl[4:] if bl.startswith("    ") else bl for bl in block)
            out.append("```")
            out.append("")
            prev_blank = True
            continue
        out.append(line)
        prev_blank = not line.strip()
        i += 1
    return "\n".join(out)


def _escape_prose(chunk):
    """Strip griffe2md markup, then escape MDX-hazardous characters in prose.

    Removes ``<code>`` wrappers and intra-page anchor links, then escapes ``<``
    and ``{``. Applied only to prose chunks, never to code.
    """
    chunk = _CODE_TAG_RE.sub("", chunk)
    chunk = _ANCHOR_LINK_RE.sub(r"\1", chunk)
    return chunk.replace("<", "&lt;").replace("{", "&#123;")


def _post_process(text):
    """Make griffe2md's Markdown safe to compile as MDX.

    Fence indented code so it survives verbatim, then rewrite only the prose
    (fenced/inline code spans are left untouched).
    """
    text = _reflow_indented_code(text)
    out = []
    for i, chunk in enumerate(_CODE_SPLIT_RE.split(text)):
        # Odd indices are the captured code spans/blocks -- leave them verbatim.
        out.append(chunk if i % 2 else _escape_prose(chunk))
    return "".join(out).rstrip("\n")


# --------------------------------------------------------------------------- #
# Module -> page
# --------------------------------------------------------------------------- #


def _relative_path(module):
    """Path of *module* relative to the top package (``""`` for slack_bolt)."""
    if module.name == PACKAGE:
        return ""
    return module.canonical_path.split(".", 1)[1].replace(".", "/")


def _iter_modules(module):
    """Yield *module* and every submodule, depth-first in source order."""
    yield module
    for member in module.members.values():
        if not member.is_alias and member.is_module:
            yield from _iter_modules(member)


# --------------------------------------------------------------------------- #
# Routes
# --------------------------------------------------------------------------- #


def _doc_id(rel_path, is_package):
    """Docs-root doc ID for a module.

    For example ``reference/app/app`` or the package overview
    ``reference/app/index``.
    """
    if not rel_path:
        base = REFERENCE_SUBDIR + "/index"
    elif is_package:
        base = "{}/{}/index".format(REFERENCE_SUBDIR, rel_path)
    else:
        base = "{}/{}".format(REFERENCE_SUBDIR, rel_path)
    return SIDEBAR_DOC_ID_PREFIX + base


def _doc_route(doc_id):
    """Absolute Docusaurus route for a doc ID (``.../index`` served at folder)."""
    route = "/" + doc_id
    if route.endswith("/index"):
        route = route[: -len("/index")]
    return route


# --------------------------------------------------------------------------- #
# Generation
# --------------------------------------------------------------------------- #


def _load_package():
    return griffe.load(
        PACKAGE,
        search_paths=[REPO_ROOT],
        docstring_parser=griffe.Parser.google,
        resolve_aliases=True,
    )


def _build_pages(root):
    """Render every module into an in-memory page record."""
    pages = {}
    for module in _iter_modules(root):
        rel_path = _relative_path(module)
        is_package = os.path.basename(str(module.filepath)) == "__init__.py"
        dotted = module.canonical_path
        # Sidebar labels use the bare final component (e.g. "error", "app");
        # the dotted path lives in the page title instead.
        sidebar_label = dotted.rsplit(".", 1)[-1]
        pages[rel_path] = {
            "module": module,
            "is_package": is_package,
            "title": dotted,
            "sidebar_label": sidebar_label,
            "doc_id": _doc_id(rel_path, is_package),
            "content": _render_module(module),
        }
    return pages


def _submodule_links(rel_path, pages):
    """Sorted child module/subpackage links for a package overview page."""
    prefix = rel_path + "/" if rel_path else ""
    depth = prefix.count("/")
    children = []
    for other_rel, page in pages.items():
        if not other_rel or not other_rel.startswith(prefix):
            continue
        if other_rel.count("/") != depth:
            continue
        children.append((page["title"], _doc_route(page["doc_id"])))
    children.sort()
    return children


def _write_pages(pages):
    reference_dir = os.path.join(DOCS_BASE_PATH, REFERENCE_SUBDIR)
    for rel_path, page in pages.items():
        if page["is_package"] or not rel_path:
            path = os.path.join(reference_dir, rel_path, "index.md")
        else:
            path = os.path.join(reference_dir, rel_path + ".md")
        os.makedirs(os.path.dirname(path), exist_ok=True)

        frontmatter = ["---", "sidebar_label: {}".format(page["sidebar_label"]), "title: {}".format(page["title"])]
        # A module whose file is <folder>/<folder>.md collides with the folder's
        # index.md route; pin it with a relative slug.
        basename = os.path.basename(path)[: -len(".md")]
        parent = os.path.basename(os.path.dirname(path))
        if basename == parent and basename != "index":
            frontmatter.append("slug: {}".format(basename))
        frontmatter.append("---")

        body_parts = []
        if page["content"]:
            body_parts.append(page["content"])
            body_parts.append("")
        if page["is_package"] or not rel_path:
            links = _submodule_links(rel_path, pages)
            if links:
                body_parts.append("## Submodules")
                body_parts.append("")
                body_parts += ["- [{}]({})".format(title, route) for title, route in links]
                body_parts.append("")

        with open(path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(frontmatter) + "\n\n" + "\n".join(body_parts).rstrip("\n") + "\n")


# --------------------------------------------------------------------------- #
# Safety gate
# --------------------------------------------------------------------------- #

_MDX_ESM_RE = re.compile(r"^(export|import)\s")


def _check_mdx_hazards():
    """Fail generation if any rendered Markdown has an MDX/acorn hazard.

    A hazard is a line outside a code fence beginning with ``export``/``import``
    (ESM) or ``<`` (JSX). These come from unfenced code examples in docstrings;
    the fix is to fence the example in its source docstring.
    """
    reference_dir = os.path.join(DOCS_BASE_PATH, REFERENCE_SUBDIR)
    hazards = []
    for dirpath, _dirnames, filenames in os.walk(reference_dir):
        for filename in filenames:
            if not filename.endswith(".md"):
                continue
            path = os.path.join(dirpath, filename)
            in_codeblock = False
            with open(path, encoding="utf-8") as handle:
                for lineno, raw in enumerate(handle, 1):
                    line = raw.rstrip("\n")
                    if line.lstrip().startswith("```"):
                        in_codeblock = not in_codeblock
                        continue
                    if in_codeblock:
                        continue
                    if _MDX_ESM_RE.match(line) or line.startswith("<"):
                        rel = os.path.relpath(path, DOCS_BASE_PATH)
                        hazards.append("{}:{}: {}".format(rel, lineno, line))
    if hazards:
        raise SystemExit(
            "MDX/acorn hazards found in generated Markdown (unfenced code at column "
            "zero). Fence the offending example in its source docstring:\n  " + "\n  ".join(hazards)
        )
    print("No MDX/acorn hazards in generated Markdown")


def main():
    # Rebuild the reference tree from scratch so renamed/removed modules don't
    # leave orphaned pages behind. Everything under reference/ is generated; the
    # nav is an autogenerated entry in _sidebar.json that reads this tree.
    reference_dir = os.path.join(DOCS_BASE_PATH, REFERENCE_SUBDIR)
    shutil.rmtree(reference_dir, ignore_errors=True)
    os.makedirs(reference_dir, exist_ok=True)
    root = _load_package()
    pages = _build_pages(root)
    _write_pages(pages)
    _check_mdx_hazards()
    print("Generated {} reference pages".format(len(pages)))


if __name__ == "__main__":
    main()
